export default [
    {    
        id: "qnfmn78itr",type:"Container",data:{},
        childBlocks:[
            {
                id:"2xhv9lspit9",type: "FrameWorkIntro",
                data:{
                    title:null,desc:null, column:null,
                    list:[
                        {
                            needHoverAnimation:false ,
                            iconUrl: "//yun.ccb.com/solution/images/icon_gray_门户网站搭建.png" , 
                            title:"门户网站搭建",
                            desc: "根据网站规模、访问量以及运营成本控制要求,灵活选择不同的产品组合,构建出入访互联网方案"
                        },{
                            needHoverAnimation:false,
                            iconUrl:"//yun.ccb.com/solution/images/icon_gray_搭建混合云.png" ,
                            title:"搭建混合云",
                            desc:"将建行云的计算存储网络资源与租户私有云连接,打造灵活、快捷的多地域网络"
                        },{
                            needHoverAnimation:true,
                            iconUrl:"//yun.ccb.com/common/images/index/solution/net-lhpz.png",
                            title:"灵活配置",
                            desc:"租户可按照自身规划,100%自定义子网、路由、网关等"
                        },{
                            needHoverAnimation:true,
                            iconUrl:"//yun.ccb.com/common/images/index/solution/net-wqgl.png",
                            title: "完全隔离",
                            desc:"通过VxLAN协议实现租户之间网络的绝对隔离,以及同租户多种不同业务的完全独立" 
                        },{
                            needHoverAnimation: true,
                            iconUrl:"//yun.ccb.com/common/images/index/solution/net-dyjr.png",
                            title:"多样接入",
                            desc:"多种云网络产品搭配,满足互联网访问、混合云等各种场景及需求"
                        },{
                            needHoverAnimation:true,
                            iconUrl:"//yun.ccb.com/common/images/index/solution/net-aqcl.png",
                            title:"金融级安全策略",
                            desc: "建设银行30年网络安全实践,打造金融级网络安全策略"
                        }
                    ],
                    bgUrl:null
                },
                ctx:{id:1,slug:"_index" ,name:"首页",committer:"system",bgColor:true,indexInParent:0},
                html:""
            }
        ],
        ctx:{id:1, slug:"_index" , name:"首页",committer:"system",bgColor:true,indexInParent:0},
        html:""
    },{
        id:"1l1mq2kbwc6",type:"Container",data:{},
        childBlocks:[
            {
                id:"l2bv6ey58nf",type:"FrameWorkIntro",
                data:{
                    title:null,desc:null,column:null,
                    list:[
                        {
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名注册.png",title:"域名注册",desc:"完成网站域名选购"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_产品选购.png",title:"产品选购",
                            desc:"在建行云购买建站所需云产品,包括安全产品、网络产品(如负载..."
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_网站建设.png",title:"网站建设",desc:"完成网站部署搭建"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名解析.png",title:"域名解析",desc:"完成域名解析服务购买与配置"
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-aqkk.png",title:"安全可靠",
                            desc:"从主机安全到流量清洗,建行云确保您的网站稳定对外服务..."
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-txkz.png",title:"弹性扩展",
                            desc:"快速扩展计算、存储、网络资源以应对交易洪峰;并随时释放多余..."
                        }
                    ],
                    noBgUrl:null
                },
                ctx:{id:1,slug:"_index",name:"首页",committer:"system",bgColor:true,indexInParent:0},
                html:""
            }
        ],
        ctx:{
            id:1,slug:"_index",name:"首页",committer:"system",bgColor:false,indexInParent:1
        },
        html:""
    },{
        id:"mhr0e1zbuk8",type:"Container",data:{},
        childBlocks:[
            {
                id:"ebh68cvjf9h",type:"FrameWorkIntro",
                data:{
                    title:null,desc:null,column:null,
                    list:[
                        {
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名注册.png",title:"域名注册",desc:"完成网站域名选购"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_产品选购.png",title:"产品选购",
                            desc:"在建行云购买建站所需云产品,包括安全产品、网络产品(如负载..."
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_网站建设.png",title:"网站建设",desc:"完成网站部署搭建"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名解析.png",title:"域名解析",desc:"完成域名解析服务购买与配置"
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-aqkk.png",title:"安全可靠",
                            desc:"从主机安全到流量清洗,建行云确保您的网站稳定对外服务..."
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-txkz.png",title:"弹性扩展",
                            desc:"快速扩展计算、存储、网络资源以应对交易洪峰;并随时释放多余..."
                        }
                    ],
                    noBgUrl:null
                },
                ctx:{id:1,slug:"_index",name:"首页",committer:"system",bgColor:true,indexInParent:0},
                html:""
            }
        ],
        ctx:{
            id:1,slug:"_index",name:"首页",committer:"system",bgColor:false,indexInParent:1
        },
        html:""
    },{
        id:"clcevji98q",type:"Container",data:{},
        childBlocks:[
            {
                id:"mwpanbr64u9",type:"FrameWorkIntro",
                data:{
                    title:null,desc:null,column:null,
                    list:[
                        {
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名注册.png",title:"域名注册",desc:"完成网站域名选购"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_产品选购.png",title:"产品选购",
                            desc:"在建行云购买建站所需云产品,包括安全产品、网络产品(如负载..."
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_网站建设.png",title:"网站建设",desc:"完成网站部署搭建"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名解析.png",title:"域名解析",desc:"完成域名解析服务购买与配置"
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-aqkk.png",title:"安全可靠",
                            desc:"从主机安全到流量清洗,建行云确保您的网站稳定对外服务..."
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-txkz.png",title:"弹性扩展",
                            desc:"快速扩展计算、存储、网络资源以应对交易洪峰;并随时释放多余..."
                        }
                    ],
                    noBgUrl:null
                },
                ctx:{id:1,slug:"_index",name:"首页",committer:"system",bgColor:true,indexInParent:0},
                html:""
            }
        ],
        ctx:{
            id:1,slug:"_index",name:"首页",committer:"system",bgColor:false,indexInParent:1
        },
        html:""
    },{
        id:"mndf9n4rghh",type:"Container",data:{},
        childBlocks:[
            {
                id:"wv172gvhzqm",type:"FrameWorkIntro",
                data:{
                    title:null,desc:null,column:null,
                    list:[
                        {
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名注册.png",title:"域名注册",desc:"完成网站域名选购"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_产品选购.png",title:"产品选购",
                            desc:"在建行云购买建站所需云产品,包括安全产品、网络产品(如负载..."
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_网站建设.png",title:"网站建设",desc:"完成网站部署搭建"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名解析.png",title:"域名解析",desc:"完成域名解析服务购买与配置"
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-aqkk.png",title:"安全可靠",
                            desc:"从主机安全到流量清洗,建行云确保您的网站稳定对外服务..."
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-txkz.png",title:"弹性扩展",
                            desc:"快速扩展计算、存储、网络资源以应对交易洪峰;并随时释放多余..."
                        }
                    ],
                    noBgUrl:null
                },
                ctx:{id:1,slug:"_index",name:"首页",committer:"system",bgColor:true,indexInParent:0},
                html:""
            }
        ],
        ctx:{
            id:1,slug:"_index",name:"首页",committer:"system",bgColor:false,indexInParent:1
        },
        html:""
    },{
        id:"lh229yy0p5",type:"Container",data:{},
        childBlocks:[
            {
                id:"71ce5dyjwyd",type:"FrameWorkIntro",
                data:{
                    title:null,desc:null,column:null,
                    list:[
                        {
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名注册.png",title:"域名注册",desc:"完成网站域名选购"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_产品选购.png",title:"产品选购",
                            desc:"在建行云购买建站所需云产品,包括安全产品、网络产品(如负载..."
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_网站建设.png",title:"网站建设",desc:"完成网站部署搭建"
                        },{
                            needHoverAnimation:false,iconUrl:"//yun.ccb.com/solution/images/icon_gray_域名解析.png",title:"域名解析",desc:"完成域名解析服务购买与配置"
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-aqkk.png",title:"安全可靠",
                            desc:"从主机安全到流量清洗,建行云确保您的网站稳定对外服务..."
                        },{
                            needHoverAnimation:true,iconUrl:"//yun.ccb.com/common/images/index/solution/website-txkz.png",title:"弹性扩展",
                            desc:"快速扩展计算、存储、网络资源以应对交易洪峰;并随时释放多余..."
                        }
                    ],
                    noBgUrl:null
                },
                ctx:{id:1,slug:"_index",name:"首页",committer:"system",bgColor:true,indexInParent:0},
                html:""
            }
        ],
        ctx:{
            id:1,slug:"_index",name:"首页",committer:"system",bgColor:false,indexInParent:1
        },
        html:""
    }
]
