export default {
    "id":"duf9vokzl7j",
    "type":"section4",
    "dataType":"single",
    "data":{
        "title":"相关产品推荐",
        "list":[
            {
                "title":"云硬盘",
                "imgUrl":"//imagecachexxfb.yun.ccb.com/static/product/aboutproduct_cloud.png",
                "linkUrl":"//yun.ccb.com/product/productcbs",
                "key":0
            },{
                "title":"虚拟专用网络VPC",
                "imgUrl":"//imagecachexxfb.yun.ccb.com/static/product/aboutproduct_selfNet.png",
                "linkUrl":"//yun.ccb.com/product/vpc1",
                "key":1
            },{
                "title":"云监控",
                "imgUrl":"//imagecachexxfb.yun.ccb.com/static/product/solution_yjk.png",
                "linkUrl":"//yun.ccb.com/solution/monitoring",
                "key":2
            },{
                "title":"容器服务",
                "imgUrl":"//imagecachexxfb.yun.ccb.com/static/product/product_rqfw.png",
                "linkUrl":"//yun.ccb.com/product/tke",
                "key":3
            }
        ]
    }
}