export default {
    "id":"67q7vnnr42m", "type":"section10", "dataType":"single",
    "data":{
        "title":"产品功能1",
        "frature":{
            "list":[
                {
                    "iconUrl":"//imagecachexxfb.yun.ccb.com/static/product/product_functions1.png",
                    "title":"多种集群类型",
                    "desc":{
                        "entityMap":{},"blocks":[
                            {
                                "key":"ffj3d",
                                "text":"根据企业自身需要，选择合适的集群规模，并可选择多种规格的容器工作节点",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    },
                    "linkText" :"多种集群类型"
                },{
                    "iconUr1":"//imagecachexxfb.yun.ccb.com/static/product/product_functions2.png",
                    "title":"Kubernetes功能增强",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"3eclc",
                                "text":"与社区版本同步更新，在开源Kubernetes基础上，增强了安全性，稳定性，可靠性",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    },
                    "linkText":"Kubernetes功能增强"
                },{
                    "iconUr1":"//imagecachexxfb.yun.ccb.com/static/product/product_functions3.png",
                    "title":"丰富的调度策略,集成负载均衡",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"4qa17",
                                "text":"有多种调度策略可供选择，集成了负载均衡服务来提供对外访问接口",
                                "type":"unstyled",
                                "depth":0,
                                "inlinestyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    },
                    "linkText" :"丰富的调度策略，集成负载均衡"
                }
            ]
        },
        "announcement":{
            "list":[
                {
                    "title":"多种集群类型",
                    "cTitle":"小集群",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"bjq03",
                                "text":"管理最大20个节点",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    }
                },{
                    "title":"多种集群类型",
                    "cTitle":"中集群",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"1sdct",
                                "text":"管理最大50个节点",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    }
                },{
                    "title":"多种集群类型",
                    "cTitle":"大集群",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"ejdvp",
                                "text":"管理最大200个节点",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    }
                },{
                    "title":"Kubernetes功能增强",
                    "cTitle":" ",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"2pj3v",
                                "text":"容器服务包含了原生Kubernetes的全部功能，同时增强了集群监控，告警，日志管理,资源控制等功能。",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    }
                },{
                    "title":"丰富的调度策略，集成负载均衡",
                    "cTitle":" ",
                    "desc":{
                        "entityMap":{},
                        "blocks":[
                            {
                                "key":"2s7vl",
                                "text":"调度策略包括亲和调度、反亲和调度和优先级调度等。可以针对不同的容器实例，绑定不同的负载均衡器，支持灰度发布功能。",
                                "type":"unstyled",
                                "depth":0,
                                "inlineStyleRanges":[],
                                "entityRanges":[],
                                "data":{}
                            }
                        ]
                    }
                }
            ]
        }
    }
}